# Generated by Django 4.1.4 on 2023-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todo_delete_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='ToDo',
        ),
    ]
