# Generated by Django 4.1.4 on 2023-02-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_name_todo_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
