# Generated by Django 4.1.4 on 2023-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_alter_message_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='manager',
        ),
    ]
